version: "3"
services:
  web:
    build:
      context: ./web
    image: web:1.0
    ports:
      - 3000:3000
    environment:
      - DATABASE=login-db
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=pass

  db:
    build:
      context: ./database
    container_name: db
    image: db:1.0
    environment:
      - MYSQL_DATABASE=login-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=xxx